Repository ViderumGlobal/ckan-cloud-operator, pull requests merged in 2019-01, with the labels that each got.

#10 misc. migration fixes
  ckan_cloud_operator/deis_ckan/ckan.py
  ckan_cloud_operator/deis_ckan/db.py
  ckan_cloud_operator/deis_ckan/instance.py
  ckan_cloud_operator/gcloud.py
  docs/IMPORT-DEIS.md
Labels: cluster, review

#11 add support for migration of storage
  ckan_cloud_operator/cli.py
  ckan_cloud_operator/deis_ckan/annotations.py
  ckan_cloud_operator/deis_ckan/ckan.py
  ckan_cloud_operator/deis_ckan/envvars.py
  ckan_cloud_operator/deis_ckan/instance.py
  ckan_cloud_operator/deis_ckan/spec.py
  ckan_cloud_operator/deis_ckan/storage.py
  ckan_cloud_operator/gcloud.py
  ckan_cloud_operator/infra.py
  ckan_cloud_operator/storage.py
  docs/IMPORT-DEIS.md
Labels: cluster, review

#12 Centralized datapushers support + migration
  ckan_cloud_operator/cli.py
  ckan_cloud_operator/datapushers.py
  ckan_cloud_operator/deis_ckan/ckan.py
  ckan_cloud_operator/deis_ckan/datapusher.py
  ckan_cloud_operator/deis_ckan/deployment.py
  ckan_cloud_operator/deis_ckan/envvars.py
  ckan_cloud_operator/infra.py
  ckan_cloud_operator/kubectl.py
  ckan_cloud_operator/routers.py
  docs/IMPORT-DEIS.md
Labels: cluster, in progress

#14 check db exists before creation
  ckan_cloud_operator/deis_ckan/db.py
Labels: review

#15 Production cluster + improvements to migration process
  ckan_cloud_operator/cli.py
  ckan_cloud_operator/deis_ckan/db.py
  ckan_cloud_operator/deis_ckan/storage.py
  ckan_cloud_operator/gcloud.py
  ckan_cloud_operator/gitlab.py
  ckan_cloud_operator/infra.py
  ckan_cloud_operator/users.py
  docs/IMPORT-DEIS.md
  docs/PRODUCTION-GCLOUD-CLUSTER.md
  environment.yaml
Labels: cluster, review

#20 get and set solr user and password explicitly
  ckan_cloud_operator/deis_ckan/envvars.py
  ckan_cloud_operator/infra.py
Labels: review

#24 handle inconsistend storage naming
  ckan_cloud_operator/deis_ckan/instance.py
  ckan_cloud_operator/deis_ckan/storage.py
Labels: review

#22 define ENVIRONMENT_NAME in activate
  ckan-cloud-operator-env.sh
Labels: review

#27 fix pip version to 18.1
  ckan_cloud_operator/gitlab.py
Labels: review

#28 fixes: routers, delete instance, self-hosted minio, migrate command
  ckan_cloud_operator/cli.py
  ckan_cloud_operator/datapushers.py
  ckan_cloud_operator/deis_ckan/annotations.py
  ckan_cloud_operator/deis_ckan/datapusher.py
  ckan_cloud_operator/deis_ckan/db.py
  ckan_cloud_operator/deis_ckan/deployment.py
  ckan_cloud_operator/deis_ckan/envvars.py
  ckan_cloud_operator/deis_ckan/instance.py
  ckan_cloud_operator/deis_ckan/migrate.py
  ckan_cloud_operator/deis_ckan/solr.py
  ckan_cloud_operator/infra.py
  ckan_cloud_operator/kubectl.py
  ckan_cloud_operator/logs.py
  ckan_cloud_operator/manager.py
  ckan_cloud_operator/routers.py
  ckan_cloud_operator/routers/__init__.py
  ckan_cloud_operator/routers/annotations.py
  ckan_cloud_operator/routers/cli.py
  ckan_cloud_operator/routers/manager.py
  ckan_cloud_operator/routers/routes/__init__.py
  ckan_cloud_operator/routers/routes/backend_url_subdomain.py
  ckan_cloud_operator/routers/routes/datapusher_subdomain.py
  ckan_cloud_operator/routers/routes/deis_instance_subdomain.py
  ckan_cloud_operator/routers/routes/manager.py
  ckan_cloud_operator/routers/traefik/__init__.py
  ckan_cloud_operator/routers/traefik/config.py
  ckan_cloud_operator/routers/traefik/deployment.py
  ckan_cloud_operator/routers/traefik/manager.py
  ckan_cloud_operator/storage.py
  ckan_cloud_operator/users.py
  docs/IMPORT-DEIS.md
  gcs-minio-proxy/Dockerfile
Labels: cluster
